/*
 * NatCrim Service Integration
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.3.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DOBFilter
 */
public class DOBFilterTest {
    private final DOBFilter model = new DOBFilter();

    /**
     * Model tests for DOBFilter
     */
    @Test
    public void testDOBFilter() {
        // TODO: test DOBFilter
    }

    /**
     * Test the property 'allowOffByOne'
     */
    @Test
    public void allowOffByOneTest() {
        // TODO: test allowOffByOne
    }

    /**
     * Test the property 'allowEmptyDob'
     */
    @Test
    public void allowEmptyDobTest() {
        // TODO: test allowEmptyDob
    }

    /**
     * Test the property 'minimumComponentsMatched'
     */
    @Test
    public void minimumComponentsMatchedTest() {
        // TODO: test minimumComponentsMatched
    }

}
