/*
 * NatCrim Service Integration
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.3.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MaxResults1
 */
public class MaxResults1Test {
    private final MaxResults1 model = new MaxResults1();

    /**
     * Model tests for MaxResults1
     */
    @Test
    public void testMaxResults1() {
        // TODO: test MaxResults1
    }

}
