# coding: utf-8

"""
    NatCrim Service Integration

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.3.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class SourceType(str, Enum):
    """
    SourceType
    """

    """
    allowed enum values
    """
    COURT = 'court'
    DOC = 'doc'
    ARREST = 'arrest'
    SOR = 'sor'
    WARRANT = 'warrant'
    SWL = 'swl'
    FEDERAL = 'federal'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SourceType from a JSON string"""
        return cls(json.loads(json_str))


