/*
 * NatCrim Service Integration
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.3.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ClientReference;
import org.openapitools.client.model.Fips;
import org.openapitools.client.model.MaxResults;
import org.openapitools.client.model.OrderSubject;
import org.openapitools.client.model.ProfileDefinitionGet;
import org.openapitools.client.model.ProfileId;
import org.openapitools.client.model.Region;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.natcrim.api.client.JSON;

/**
 * OrderRequestGet
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-30T02:54:25.572047Z[Etc/UTC]")
public class OrderRequestGet {
  public static final String SERIALIZED_NAME_CLIENT_REFERENCE = "client_reference";
  @SerializedName(SERIALIZED_NAME_CLIENT_REFERENCE)
  private ClientReference clientReference;

  public static final String SERIALIZED_NAME_PROFILE_ID = "profile_id";
  @SerializedName(SERIALIZED_NAME_PROFILE_ID)
  private ProfileId profileId;

  public static final String SERIALIZED_NAME_PROFILE_DEF = "profile_def";
  @SerializedName(SERIALIZED_NAME_PROFILE_DEF)
  private ProfileDefinitionGet profileDef;

  public static final String SERIALIZED_NAME_FIPS = "fips";
  @SerializedName(SERIALIZED_NAME_FIPS)
  private Fips fips = 00000;

  public static final String SERIALIZED_NAME_REGION = "region";
  @SerializedName(SERIALIZED_NAME_REGION)
  private Region region;

  public static final String SERIALIZED_NAME_SUBJECT = "subject";
  @SerializedName(SERIALIZED_NAME_SUBJECT)
  private OrderSubject subject;

  public static final String SERIALIZED_NAME_MAX_RESULTS = "max_results";
  @SerializedName(SERIALIZED_NAME_MAX_RESULTS)
  private MaxResults maxResults;

  public OrderRequestGet() {
  }

  public OrderRequestGet clientReference(ClientReference clientReference) {
    
    this.clientReference = clientReference;
    return this;
  }

   /**
   * Get clientReference
   * @return clientReference
  **/
  @javax.annotation.Nonnull
  public ClientReference getClientReference() {
    return clientReference;
  }


  public void setClientReference(ClientReference clientReference) {
    this.clientReference = clientReference;
  }


  public OrderRequestGet profileId(ProfileId profileId) {
    
    this.profileId = profileId;
    return this;
  }

   /**
   * Get profileId
   * @return profileId
  **/
  @javax.annotation.Nonnull
  public ProfileId getProfileId() {
    return profileId;
  }


  public void setProfileId(ProfileId profileId) {
    this.profileId = profileId;
  }


  public OrderRequestGet profileDef(ProfileDefinitionGet profileDef) {
    
    this.profileDef = profileDef;
    return this;
  }

   /**
   * Get profileDef
   * @return profileDef
  **/
  @javax.annotation.Nonnull
  public ProfileDefinitionGet getProfileDef() {
    return profileDef;
  }


  public void setProfileDef(ProfileDefinitionGet profileDef) {
    this.profileDef = profileDef;
  }


  public OrderRequestGet fips(Fips fips) {
    
    this.fips = fips;
    return this;
  }

   /**
   * Get fips
   * @return fips
  **/
  @javax.annotation.Nullable
  public Fips getFips() {
    return fips;
  }


  public void setFips(Fips fips) {
    this.fips = fips;
  }


  public OrderRequestGet region(Region region) {
    
    this.region = region;
    return this;
  }

   /**
   * Get region
   * @return region
  **/
  @javax.annotation.Nullable
  public Region getRegion() {
    return region;
  }


  public void setRegion(Region region) {
    this.region = region;
  }


  public OrderRequestGet subject(OrderSubject subject) {
    
    this.subject = subject;
    return this;
  }

   /**
   * Get subject
   * @return subject
  **/
  @javax.annotation.Nonnull
  public OrderSubject getSubject() {
    return subject;
  }


  public void setSubject(OrderSubject subject) {
    this.subject = subject;
  }


  public OrderRequestGet maxResults(MaxResults maxResults) {
    
    this.maxResults = maxResults;
    return this;
  }

   /**
   * Get maxResults
   * @return maxResults
  **/
  @javax.annotation.Nullable
  public MaxResults getMaxResults() {
    return maxResults;
  }


  public void setMaxResults(MaxResults maxResults) {
    this.maxResults = maxResults;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderRequestGet orderRequestGet = (OrderRequestGet) o;
    return Objects.equals(this.clientReference, orderRequestGet.clientReference) &&
        Objects.equals(this.profileId, orderRequestGet.profileId) &&
        Objects.equals(this.profileDef, orderRequestGet.profileDef) &&
        Objects.equals(this.fips, orderRequestGet.fips) &&
        Objects.equals(this.region, orderRequestGet.region) &&
        Objects.equals(this.subject, orderRequestGet.subject) &&
        Objects.equals(this.maxResults, orderRequestGet.maxResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientReference, profileId, profileDef, fips, region, subject, maxResults);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderRequestGet {\n");
    sb.append("    clientReference: ").append(toIndentedString(clientReference)).append("\n");
    sb.append("    profileId: ").append(toIndentedString(profileId)).append("\n");
    sb.append("    profileDef: ").append(toIndentedString(profileDef)).append("\n");
    sb.append("    fips: ").append(toIndentedString(fips)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    maxResults: ").append(toIndentedString(maxResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("client_reference");
    openapiFields.add("profile_id");
    openapiFields.add("profile_def");
    openapiFields.add("fips");
    openapiFields.add("region");
    openapiFields.add("subject");
    openapiFields.add("max_results");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("client_reference");
    openapiRequiredFields.add("profile_id");
    openapiRequiredFields.add("profile_def");
    openapiRequiredFields.add("subject");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to OrderRequestGet
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OrderRequestGet.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OrderRequestGet is not found in the empty JSON string", OrderRequestGet.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OrderRequestGet.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OrderRequestGet` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : OrderRequestGet.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `client_reference`
      ClientReference.validateJsonElement(jsonObj.get("client_reference"));
      // validate the required field `profile_id`
      ProfileId.validateJsonElement(jsonObj.get("profile_id"));
      // validate the required field `profile_def`
      ProfileDefinitionGet.validateJsonElement(jsonObj.get("profile_def"));
      // validate the optional field `fips`
      if (jsonObj.get("fips") != null && !jsonObj.get("fips").isJsonNull()) {
        Fips.validateJsonElement(jsonObj.get("fips"));
      }
      // validate the optional field `region`
      if (jsonObj.get("region") != null && !jsonObj.get("region").isJsonNull()) {
        Region.validateJsonElement(jsonObj.get("region"));
      }
      // validate the required field `subject`
      OrderSubject.validateJsonElement(jsonObj.get("subject"));
      // validate the optional field `max_results`
      if (jsonObj.get("max_results") != null && !jsonObj.get("max_results").isJsonNull()) {
        MaxResults.validateJsonElement(jsonObj.get("max_results"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OrderRequestGet.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OrderRequestGet' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OrderRequestGet> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OrderRequestGet.class));

       return (TypeAdapter<T>) new TypeAdapter<OrderRequestGet>() {
           @Override
           public void write(JsonWriter out, OrderRequestGet value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OrderRequestGet read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OrderRequestGet given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OrderRequestGet
  * @throws IOException if the JSON string is invalid with respect to OrderRequestGet
  */
  public static OrderRequestGet fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OrderRequestGet.class);
  }

 /**
  * Convert an instance of OrderRequestGet to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

