/*
 * NatCrim Service Integration
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.3.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.DOBFilter;
import org.openapitools.client.model.NameFilter;
import org.openapitools.client.model.ProfileDefinitionMaxAge;
import org.openapitools.client.model.SourceTypes;
import org.openapitools.client.model.Tag;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.natcrim.api.client.JSON;

/**
 * ProfileDefinition
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-18T03:26:01.936040Z[Etc/UTC]")
public class ProfileDefinition {
  public static final String SERIALIZED_NAME_TAG = "tag";
  @SerializedName(SERIALIZED_NAME_TAG)
  private Tag tag;

  public static final String SERIALIZED_NAME_FIRST_NAME = "first_name";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  private NameFilter firstName;

  public static final String SERIALIZED_NAME_MIDDLE_NAME = "middle_name";
  @SerializedName(SERIALIZED_NAME_MIDDLE_NAME)
  private NameFilter middleName;

  public static final String SERIALIZED_NAME_LAST_NAME = "last_name";
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  private NameFilter lastName;

  public static final String SERIALIZED_NAME_DOB = "dob";
  @SerializedName(SERIALIZED_NAME_DOB)
  private DOBFilter dob;

  public static final String SERIALIZED_NAME_SOURCE_TYPES = "source_types";
  @SerializedName(SERIALIZED_NAME_SOURCE_TYPES)
  private SourceTypes sourceTypes = [];

  public static final String SERIALIZED_NAME_MAX_AGE = "max_age";
  @SerializedName(SERIALIZED_NAME_MAX_AGE)
  private ProfileDefinitionMaxAge maxAge = {age=99, max_age_field=filed};

  public ProfileDefinition() {
  }

  public ProfileDefinition tag(Tag tag) {
    
    this.tag = tag;
    return this;
  }

   /**
   * Get tag
   * @return tag
  **/
  @javax.annotation.Nullable
  public Tag getTag() {
    return tag;
  }


  public void setTag(Tag tag) {
    this.tag = tag;
  }


  public ProfileDefinition firstName(NameFilter firstName) {
    
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @javax.annotation.Nonnull
  public NameFilter getFirstName() {
    return firstName;
  }


  public void setFirstName(NameFilter firstName) {
    this.firstName = firstName;
  }


  public ProfileDefinition middleName(NameFilter middleName) {
    
    this.middleName = middleName;
    return this;
  }

   /**
   * Get middleName
   * @return middleName
  **/
  @javax.annotation.Nonnull
  public NameFilter getMiddleName() {
    return middleName;
  }


  public void setMiddleName(NameFilter middleName) {
    this.middleName = middleName;
  }


  public ProfileDefinition lastName(NameFilter lastName) {
    
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @javax.annotation.Nonnull
  public NameFilter getLastName() {
    return lastName;
  }


  public void setLastName(NameFilter lastName) {
    this.lastName = lastName;
  }


  public ProfileDefinition dob(DOBFilter dob) {
    
    this.dob = dob;
    return this;
  }

   /**
   * Get dob
   * @return dob
  **/
  @javax.annotation.Nonnull
  public DOBFilter getDob() {
    return dob;
  }


  public void setDob(DOBFilter dob) {
    this.dob = dob;
  }


  public ProfileDefinition sourceTypes(SourceTypes sourceTypes) {
    
    this.sourceTypes = sourceTypes;
    return this;
  }

   /**
   * Get sourceTypes
   * @return sourceTypes
  **/
  @javax.annotation.Nullable
  public SourceTypes getSourceTypes() {
    return sourceTypes;
  }


  public void setSourceTypes(SourceTypes sourceTypes) {
    this.sourceTypes = sourceTypes;
  }


  public ProfileDefinition maxAge(ProfileDefinitionMaxAge maxAge) {
    
    this.maxAge = maxAge;
    return this;
  }

   /**
   * Get maxAge
   * @return maxAge
  **/
  @javax.annotation.Nullable
  public ProfileDefinitionMaxAge getMaxAge() {
    return maxAge;
  }


  public void setMaxAge(ProfileDefinitionMaxAge maxAge) {
    this.maxAge = maxAge;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileDefinition profileDefinition = (ProfileDefinition) o;
    return Objects.equals(this.tag, profileDefinition.tag) &&
        Objects.equals(this.firstName, profileDefinition.firstName) &&
        Objects.equals(this.middleName, profileDefinition.middleName) &&
        Objects.equals(this.lastName, profileDefinition.lastName) &&
        Objects.equals(this.dob, profileDefinition.dob) &&
        Objects.equals(this.sourceTypes, profileDefinition.sourceTypes) &&
        Objects.equals(this.maxAge, profileDefinition.maxAge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tag, firstName, middleName, lastName, dob, sourceTypes, maxAge);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileDefinition {\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    middleName: ").append(toIndentedString(middleName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    dob: ").append(toIndentedString(dob)).append("\n");
    sb.append("    sourceTypes: ").append(toIndentedString(sourceTypes)).append("\n");
    sb.append("    maxAge: ").append(toIndentedString(maxAge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("tag");
    openapiFields.add("first_name");
    openapiFields.add("middle_name");
    openapiFields.add("last_name");
    openapiFields.add("dob");
    openapiFields.add("source_types");
    openapiFields.add("max_age");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("first_name");
    openapiRequiredFields.add("middle_name");
    openapiRequiredFields.add("last_name");
    openapiRequiredFields.add("dob");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ProfileDefinition
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ProfileDefinition.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ProfileDefinition is not found in the empty JSON string", ProfileDefinition.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ProfileDefinition.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ProfileDefinition` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ProfileDefinition.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `tag`
      if (jsonObj.get("tag") != null && !jsonObj.get("tag").isJsonNull()) {
        Tag.validateJsonElement(jsonObj.get("tag"));
      }
      // validate the required field `first_name`
      NameFilter.validateJsonElement(jsonObj.get("first_name"));
      // validate the required field `middle_name`
      NameFilter.validateJsonElement(jsonObj.get("middle_name"));
      // validate the required field `last_name`
      NameFilter.validateJsonElement(jsonObj.get("last_name"));
      // validate the required field `dob`
      DOBFilter.validateJsonElement(jsonObj.get("dob"));
      // validate the optional field `source_types`
      if (jsonObj.get("source_types") != null && !jsonObj.get("source_types").isJsonNull()) {
        SourceTypes.validateJsonElement(jsonObj.get("source_types"));
      }
      // validate the optional field `max_age`
      if (jsonObj.get("max_age") != null && !jsonObj.get("max_age").isJsonNull()) {
        ProfileDefinitionMaxAge.validateJsonElement(jsonObj.get("max_age"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProfileDefinition.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProfileDefinition' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProfileDefinition> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProfileDefinition.class));

       return (TypeAdapter<T>) new TypeAdapter<ProfileDefinition>() {
           @Override
           public void write(JsonWriter out, ProfileDefinition value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ProfileDefinition read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ProfileDefinition given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ProfileDefinition
  * @throws IOException if the JSON string is invalid with respect to ProfileDefinition
  */
  public static ProfileDefinition fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProfileDefinition.class);
  }

 /**
  * Convert an instance of ProfileDefinition to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

