# coding: utf-8

"""
    NatCrim Service Integration

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.3.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from natcrim_api_client.models.max_age_get import MaxAgeGet

class TestMaxAgeGet(unittest.TestCase):
    """MaxAgeGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MaxAgeGet:
        """Test MaxAgeGet
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MaxAgeGet`
        """
        model = MaxAgeGet()
        if include_optional:
            return MaxAgeGet(
                age = 56,
                max_age_field = 'filed'
            )
        else:
            return MaxAgeGet(
        )
        """

    def testMaxAgeGet(self):
        """Test MaxAgeGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
