# coding: utf-8

"""
    NatCrim Service Integration

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.3.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from natcrim_api_client.models.order_post import OrderPost

class TestOrderPost(unittest.TestCase):
    """OrderPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderPost:
        """Test OrderPost
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderPost`
        """
        model = OrderPost()
        if include_optional:
            return OrderPost(
                sub_account_id = '',
                request = natcrim_api_client.models.order_request_post.OrderRequestPost(
                    client_reference = null, 
                    profile_id = null, 
                    profile_def = null, 
                    fips = null, 
                    region = null, 
                    subject = natcrim_api_client.models.order_subject.OrderSubject(
                        first_name = null, 
                        middle_name = null, 
                        last_name = null, 
                        dob = null, ), 
                    max_results = null, )
            )
        else:
            return OrderPost(
                request = natcrim_api_client.models.order_request_post.OrderRequestPost(
                    client_reference = null, 
                    profile_id = null, 
                    profile_def = null, 
                    fips = null, 
                    region = null, 
                    subject = natcrim_api_client.models.order_subject.OrderSubject(
                        first_name = null, 
                        middle_name = null, 
                        last_name = null, 
                        dob = null, ), 
                    max_results = null, ),
        )
        """

    def testOrderPost(self):
        """Test OrderPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
