# coding: utf-8

"""
    NatCrim Service Integration

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.3.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from natcrim_api_client.models.order_post_response_output import OrderPostResponseOutput

class TestOrderPostResponseOutput(unittest.TestCase):
    """OrderPostResponseOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderPostResponseOutput:
        """Test OrderPostResponseOutput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderPostResponseOutput`
        """
        model = OrderPostResponseOutput()
        if include_optional:
            return OrderPostResponseOutput(
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                sub_account_id = '',
                result = natcrim_api_client.models.order_result.OrderResult(
                    completed_at = null, 
                    failure = null, 
                    success = null, 
                    max_results = null, ),
                content = None
            )
        else:
            return OrderPostResponseOutput(
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                sub_account_id = '',
                result = natcrim_api_client.models.order_result.OrderResult(
                    completed_at = null, 
                    failure = null, 
                    success = null, 
                    max_results = null, ),
                content = None,
        )
        """

    def testOrderPostResponseOutput(self):
        """Test OrderPostResponseOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
