# coding: utf-8

"""
    NatCrim Service Integration

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.3.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from natcrim_api_client.models.dob_filter_get import DOBFilterGet

class TestDOBFilterGet(unittest.TestCase):
    """DOBFilterGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DOBFilterGet:
        """Test DOBFilterGet
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DOBFilterGet`
        """
        model = DOBFilterGet()
        if include_optional:
            return DOBFilterGet(
                allow_off_by_one = True,
                allow_empty_dob = True,
                minimum_components_matched = 0.0
            )
        else:
            return DOBFilterGet(
        )
        """

    def testDOBFilterGet(self):
        """Test DOBFilterGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
