/**
 * NatCrim Service Integration
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.3.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NatcrimApiClient);
  }
}(this, function(expect, NatcrimApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NatcrimApiClient.NameFilterGet();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NameFilterGet', function() {
    it('should create an instance of NameFilterGet', function() {
      // uncomment below and update the code to test NameFilterGet
      //var instance = new NatcrimApiClient.NameFilterGet();
      //expect(instance).to.be.a(NatcrimApiClient.NameFilterGet);
    });

    it('should have the property matchRequired (base name: "match_required")', function() {
      // uncomment below and update the code to test the property matchRequired
      //var instance = new NatcrimApiClient.NameFilterGet();
      //expect(instance).to.be();
    });

    it('should have the property matchFirstLetters (base name: "match_first_letters")', function() {
      // uncomment below and update the code to test the property matchFirstLetters
      //var instance = new NatcrimApiClient.NameFilterGet();
      //expect(instance).to.be();
    });

    it('should have the property matchBeginsWith (base name: "match_begins_with")', function() {
      // uncomment below and update the code to test the property matchBeginsWith
      //var instance = new NatcrimApiClient.NameFilterGet();
      //expect(instance).to.be();
    });

    it('should have the property matchFullName (base name: "match_full_name")', function() {
      // uncomment below and update the code to test the property matchFullName
      //var instance = new NatcrimApiClient.NameFilterGet();
      //expect(instance).to.be();
    });

  });

}));
