/**
 * NatCrim Service Integration
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.3.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DOBFilterGet model module.
 * @module model/DOBFilterGet
 * @version 1.0.0
 */
class DOBFilterGet {
    /**
     * Constructs a new <code>DOBFilterGet</code>.
     * @alias module:model/DOBFilterGet
     */
    constructor() { 
        
        DOBFilterGet.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DOBFilterGet</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DOBFilterGet} obj Optional instance to populate.
     * @return {module:model/DOBFilterGet} The populated <code>DOBFilterGet</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DOBFilterGet();

            if (data.hasOwnProperty('allow_off_by_one')) {
                obj['allow_off_by_one'] = ApiClient.convertToType(data['allow_off_by_one'], 'Boolean');
            }
            if (data.hasOwnProperty('allow_empty_dob')) {
                obj['allow_empty_dob'] = ApiClient.convertToType(data['allow_empty_dob'], 'Boolean');
            }
            if (data.hasOwnProperty('minimum_components_matched')) {
                obj['minimum_components_matched'] = ApiClient.convertToType(data['minimum_components_matched'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DOBFilterGet</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DOBFilterGet</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} allow_off_by_one
 * @default false
 */
DOBFilterGet.prototype['allow_off_by_one'] = false;

/**
 * @member {Boolean} allow_empty_dob
 * @default false
 */
DOBFilterGet.prototype['allow_empty_dob'] = false;

/**
 * @member {Number} minimum_components_matched
 * @default 3
 */
DOBFilterGet.prototype['minimum_components_matched'] = 3;






export default DOBFilterGet;

