/**
 * NatCrim Service Integration
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.3.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MaxAgeFieldSelector.
* @enum {}
* @readonly
*/
export default class MaxAgeFieldSelector {
    
        /**
         * value: "filed"
         * @const
         */
        "filed" = "filed";

    
        /**
         * value: "disposition"
         * @const
         */
        "disposition" = "disposition";

    

    /**
    * Returns a <code>MaxAgeFieldSelector</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/MaxAgeFieldSelector} The enum <code>MaxAgeFieldSelector</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

