/**
 * NatCrim Service Integration
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.3.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NameFilter model module.
 * @module model/NameFilter
 * @version 1.0.0
 */
class NameFilter {
    /**
     * Constructs a new <code>NameFilter</code>.
     * @alias module:model/NameFilter
     */
    constructor() { 
        
        NameFilter.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NameFilter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NameFilter} obj Optional instance to populate.
     * @return {module:model/NameFilter} The populated <code>NameFilter</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NameFilter();

            if (data.hasOwnProperty('match_required')) {
                obj['match_required'] = ApiClient.convertToType(data['match_required'], 'Boolean');
            }
            if (data.hasOwnProperty('match_first_letters')) {
                obj['match_first_letters'] = ApiClient.convertToType(data['match_first_letters'], 'Number');
            }
            if (data.hasOwnProperty('match_begins_with')) {
                obj['match_begins_with'] = ApiClient.convertToType(data['match_begins_with'], 'Boolean');
            }
            if (data.hasOwnProperty('match_full_name')) {
                obj['match_full_name'] = ApiClient.convertToType(data['match_full_name'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NameFilter</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NameFilter</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} match_required
 * @default true
 */
NameFilter.prototype['match_required'] = true;

/**
 * @member {Number} match_first_letters
 * @default 0
 */
NameFilter.prototype['match_first_letters'] = 0;

/**
 * @member {Boolean} match_begins_with
 * @default false
 */
NameFilter.prototype['match_begins_with'] = false;

/**
 * @member {Boolean} match_full_name
 * @default true
 */
NameFilter.prototype['match_full_name'] = true;






export default NameFilter;

