/*
 * NatCrim Service Integration
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.3.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import com.natcrim.api.client.ApiException;
import org.openapitools.client.model.Me;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PrincipalApi
 */
@Disabled
public class PrincipalApiTest {

    private final PrincipalApi api = new PrincipalApi();

    /**
     * Get Me
     *
     * Principal attributes
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMeMeGetTest() throws ApiException {
        Me response = api.getMeMeGet();
        // TODO: test validations
    }

}
